name: 'Sonar Cloud Scan and pytest report'

on:
  push:
    branches: [main]

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout to Repo
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
